bensin=float(input("hur mycket bensin tankade du i liter? "))
pris=float(input("hur mycket kostar bensinen i kr per liter? "))
total=float(bensin*pris)
print( "+---------------------------+")
print("| KVITTO                     |")
print("| Tankad volym:              |")
print("| ",bensin,"liter            |")
print("| Pris per liter:            |")
print("|     ",pris,"kr             |")
print("|                            |")
print("| Betalt kronor              |")
print("| ",total,"kr                |")
print("|                            |")
print("|                            |")
print("| Tack för besöket och       |")
print("| välkommen åter!            |")
print("+---------------------------+")
